name: BOM Rainfall Update

on:
  workflow_dispatch:
  schedule:
   # ~4:00 AM NSW time (overnight refresh)
    - cron: '0 16 * * *'
  # ~11:00 AM NSW time (morning refresh)
    - cron: '0 0 * * *'

    # ~2:00 PM NSW time (midday stability refresh)
    - cron: '0 3 * * *'

    # ~4:00 PM NSW time (afternoon refresh)
    - cron: '0 5 * * *'

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 pandas

      - name: Run BOM script
        run: python bom.py

      # lets you download the CSV from the run
      - name: Upload CSV as artifact
        uses: actions/upload-artifact@v4
        with:
          name: bom-data
          path: bom_rainfall.csv

      # saves CSV into your repo
      - name: Commit CSV to repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add bom_rainfall.csv
          git commit -m "update BOM rainfall" || echo "No changes to commit"
          git push
