name: BOM Rainfall Update

on:
  schedule:
    - cron: '0 1 * * *'   # once per day (UTC time)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install libraries
        run: pip install requests beautifulsoup4 pandas

      - name: Run script
        run: python Update bom.py

      - name: Commit output
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add bom_rainfall.csv
          git commit -m "update rainfall" || exit 0
          git push
